version: '3.7'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    command: ["postgres", "-c", "log_statement=all"]